# Railway deployment configuration for untagle-backend

# This file is optional - Railway auto-detects Node.js projects
# Uncomment and customize if needed

[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
